package com.purcotton.engine;
import com.purcotton.omni.promotion.rule.bean.Person;
rule "rule1"
  no-loop true
  when
     $p: Person(name=="张三")
  then
     System.out.println("rule1规则执行");
  end

 rule "rule2"
   no-loop true
   when
      $p: Person(age==20)
   then
     System.out.println("rule2规则执行");
   end

 rule "规则"
   no-loop true
   when
      eval(true)
   then
     System.out.println("rule2规则执行");
   end