package com.purcotton.engine;
import com.purcotton.omni.promotion.rule.bean.Person;
rule "rule1"
  no-loop true
  when
     $p: Person(name=="张三")
  then
     $p.setAge(50);
     update($p);
     System.out.println("设置noloop的效果");
  end

//rule "rule2"
//  no-loop true
//  when
//     p: Person(age == 50)
//  then
//     p.setName("李四");
//     update(p);
//     System.out.println("设置noloop的效果:"+p.getName());
//  end
