package com.purcotton;
import com.purcotton.omni.promotion.rule.bean.Student;
import java.util.ArrayList;

rule "rule1"
   when
       //过滤一班的学生,注意collect后面的部分要括号
       $list:ArrayList() from collect (Student(className=="一班"))
   then
       System.out.println("rule1规则匹配成功$p:"+$list.size());
   end

rule "rule2 pattern"
when
    //过滤一班的学生,注意collect后面的部分要括号
    $list:ArrayList(size>=2) from collect (Student(className=="二班"))
then
    System.out.println("rule2 pattern规则匹配成功$p:"+$list.size());
end