package com.purcotton;
import com.purcotton.omni.promotion.rule.bean.Employ;;
  
rule"Award"  
       ruleflow-group"award_punish"  
when  
   emp:Employ(awardPunish=="award")  
then  
   System.out.println("execrule Award ... ");  
  emp.setPercent(1.10);  
end
  
rule"Punishment"  
       ruleflow-group"award_punish"  
when  
   emp:Employ(awardPunish=="punish")  
then  
   System.out.println("execrule Punishment ... ");  
  emp.setPercent(0.90);  
end  
  
rule"None"  
      ruleflow-group"award_punish"  
when  
   emp:Employ(awardPunish=="none")  
then  
   System.out.println("execrule None ... ");  
  emp.setPercent(1.00);  
end 